# This is a basic workflow to help you get started with Actions

name: Branch Operations

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: 
        - closed
    branches:
        - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkBranch:
    name: Branch Operation
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
        branch:  ${{ steps.branch.outputs.branch }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Lock Branch
        id: branch
        run: |
            echo "branch=${GITHUB_HEAD_REF}" >> "$GITHUB_OUTPUT"
  debug:
    runs-on: ubuntu-latest
    needs: checkBranch
    steps:
      - env:
          OUTPUT2: ${{needs.checkBranch.outputs.branch}}
        run: echo "$OUTPUT2"
  
  lock-branch:
    runs-on: ubuntu-latest
    needs: checkBranch
    steps:
      - uses: actions/checkout@v3
      - env:
         BRANCH_NAME: ${{needs.checkBranch.outputs.branch}}
        run: |
            # Replace 'main' with the branch you want to lock
            # Lock the branch
            git checkout $BRANCH_NAME
            git tag Locked
            git push origin $BRANCH_NAME
